[package]
name = "rust"
version = "0.1.0"
authors = ["Ilya Sheprut <optozorax@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.6.3"
itertools = "0.9.0"
colored = "1.9.3"